pretrained_base_model_path: "/home/date1/hjq/repository/BaseModels/stable-diffusion-v1-5"
pretrained_vae_path: "/home/date1/hjq/repository/magic-animate/pretrained_models/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./exp_output/stage1/denoising_unet-25620.pth"
reference_unet_path: "./exp_output/stage1/reference_unet-25620.pth"
pose_guider_path: "./exp_output/stage1/pose_guider-25620.pth"
motion_module_path: "./exp_output/stage2/motion_module-16400.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/km3/image1.jpg":
    - "./configs/inference/km3/image1.mp4" 
  "./configs/inference/km3/image2.jpg":
    - "./configs/inference/km3/image2.mp4"
  "./configs/inference/km3/image3.jpg":
    - "./configs/inference/km3/image3.mp4"
  "./configs/inference/km3/image4.jpg":
    - "./configs/inference/km3/image4.mp4"
  "./configs/inference/km3/image5.jpg":
    - "./configs/inference/km3/image5.mp4"
  "./configs/inference/km3/image6.jpg":
    - "./configs/inference/km3/image6.mp4"
