pretrained_base_model_path: "/home/date1/hjq/repository/BaseModels/stable-diffusion-v1-5"
pretrained_vae_path: "/home/date1/hjq/repository/magic-animate/pretrained_models/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./exp_output/stage1/denoising_unet-29900.pth"
reference_unet_path: "./exp_output/stage1/reference_unet-29900.pth"
pose_guider_path: "./exp_output/stage1/pose_guider-29900.pth"
motion_module_path: "./exp_output/stage2-/motion_module_a100-8800.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/ref_images/self/image1.jpg":
    - "./configs/inference/BathSong/image1.mp4" 
  "./configs/inference/ref_images/self/image2.jpg":
    - "./configs/inference/BathSong/image2.mp4"
  "./configs/inference/ref_images/self/image3.jpg":
    - "./configs/inference/BathSong/image3.mp4"
  # "./configs/inference/ref_images/self/image4.jpg":
  #   - "./configs/inference/km3/image4.mp4"
  # "./configs/inference/ref_images/self/image5.jpg":
  #   - "./configs/inference/km3/image5.mp4"
  # "./configs/inference/ref_images/self/image6.jpg":
  #   - "./configs/inference/km3/image6.mp4"
  # BathSong
